name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    # --- Setup for Headed Mode (using xvfb) ---
    - name: Install XVFB
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Run Playwright tests in Headed Mode with XVFB
      # We use 'xvfb-run' to start Playwright within a virtual display
      run: xvfb-run --auto-display npx playwright test --headed
      env:
        # Important: Set DISPLAY environment variable for headed mode
        DISPLAY: ':99' # This is the default display used by xvfb-run --auto-display

    # --- Upload Playwright Report ---
    - name: Upload Playwright Report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30 # Optional: How long to retain the artifact

    # --- Upload Test Results (including screenshots and videos) ---
    - name: Upload Test Results
      if: always() # Always upload results, even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: playwright-test-results
        path: test-results/
        retention-days: 30 # Optional: How long to retain the artifact
